"""add previous_vdb_ids to conversation

Revision ID: 2c57798ecb54
Revises: bb8a7269748f
Create Date: 2025-07-22 17:24:50.594655

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2c57798ecb54"
down_revision: Union[str, Sequence[str], None] = "bb8a7269748f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "conversations",
        sa.Column("previous_vdb_ids", sa.JSON(), nullable=False, server_default="[]"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("conversations", "previous_vdb_ids")
    # ### end Alembic commands ###
