"""Add fields for data download to message model

Revision ID: 984539c31617
Revises:
Create Date: 2025-06-25 00:10:31.483002

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "984539c31617"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("messages", sa.Column("download_link", sa.Text(), nullable=True))
    op.add_column("messages", sa.Column("request_id", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("messages", "request_id")
    op.drop_column("messages", "download_link")
    # ### end Alembic commands ###
