substitutions:
  _IMAGE_NAME: docker.io/milesssssss/nautichat-backend

steps:

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_IMAGE_NAME}:$SHORT_SHA', '.']

# Log in & push to Docker Hub
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: bash
  secretEnv: ['DH_USER','DH_PASS']
  args:
    - -c
    - |
      echo "$$DH_PASS" | docker login -u "$$DH_USER" --password-stdin
      docker push "${_IMAGE_NAME}:$SHORT_SHA"

# Deploy to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    ['run','deploy','fastapi-service',
     '--image=${_IMAGE_NAME}:$SHORT_SHA',
     '--region=northamerica-west1',   
     '--platform=managed',
     '--port=8080',
     '--allow-unauthenticated',
     '--quiet']

images:
- '${_IMAGE_NAME}:$SHORT_SHA'

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/dockerhub-user/versions/latest
    env: DH_USER
  - versionName: projects/$PROJECT_ID/secrets/dockerhub-pass/versions/latest
    env: DH_PASS

options:
  logging: CLOUD_LOGGING_ONLY
