services:
  backend:
    image: milesssssss/nautichat-backend:latest
    ports:
      - "8000:8080"
    env_file:
      - ./backend-api/.env
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    stop_grace_period: 10s
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 20
      start_period: 1200s

  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: backend

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    depends_on:
      - backend
    command: tunnel run nautichat-backend
    volumes:
      - ~/.cloudflared:/home/nonroot/.cloudflared
