"""add unique constraint on vector_documents(source, name)

Revision ID: 52726b3af26e
Revises: f8eea6f10b2c
Create Date: 2025-07-15 10:55:51.978446

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "52726b3af26e"
down_revision: Union[str, Sequence[str], None] = "f8eea6f10b2c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_vector_source_name", "vector_documents", ["source", "name"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_vector_source_name", "vector_documents", type_="unique")
    # ### end Alembic commands ###
