"""Remove name field

Revision ID: fd0f30e1d4e6
Revises: ec7c9ea3266c
Create Date: 2025-07-15 12:26:02.269373

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fd0f30e1d4e6"
down_revision: Union[str, Sequence[str], None] = "ec7c9ea3266c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_vector_source_name"), "vector_documents", type_="unique"
    )
    op.drop_index(op.f("ix_vector_documents_source"), table_name="vector_documents")
    op.create_index(
        op.f("ix_vector_documents_source"), "vector_documents", ["source"], unique=True
    )
    op.create_unique_constraint("uq_vector_source", "vector_documents", ["source"])
    op.drop_column("vector_documents", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vector_documents",
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_constraint("uq_vector_source", "vector_documents", type_="unique")
    op.drop_index(op.f("ix_vector_documents_source"), table_name="vector_documents")
    op.create_index(
        op.f("ix_vector_documents_source"), "vector_documents", ["source"], unique=False
    )
    op.create_unique_constraint(
        op.f("uq_vector_source_name"),
        "vector_documents",
        ["source", "name"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
