"""remove download link from message

Revision ID: 64a2040253b3
Revises: 984539c31617
Create Date: 2025-07-10 18:01:24.750325

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "64a2040253b3"
down_revision: Union[str, Sequence[str], None] = "984539c31617"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("messages", "download_link")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "messages",
        sa.Column("download_link", sa.TEXT(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
