"""add obtained params dict to Conversation, add message fields

Revision ID: bb8a7269748f
Revises: 134fa35fb62b
Create Date: 2025-07-17 16:26:02.043462

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bb8a7269748f"
down_revision: Union[str, Sequence[str], None] = "134fa35fb62b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "conversations",
        sa.Column("obtained_params", sa.JSON(), nullable=False, server_default="{}"),
    )
    op.add_column("messages", sa.Column("onc_api_url", sa.String(), nullable=True))
    op.add_column("messages", sa.Column("citation", sa.String(), nullable=True))
    op.add_column(
        "messages", sa.Column("sources", sa.JSON(), nullable=False, server_default="[]")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("messages", "sources")
    op.drop_column("messages", "citation")
    op.drop_column("messages", "onc_api_url")
    op.drop_column("conversations", "obtained_params")
    # ### end Alembic commands ###
