"""create vector_documents table

Revision ID: f8eea6f10b2c
Revises: 64a2040253b3
Create Date: 2025-07-15 09:43:18.357841

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f8eea6f10b2c"
down_revision: Union[str, Sequence[str], None] = "64a2040253b3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vector_documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("usage_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_vector_documents_id"), "vector_documents", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_vector_documents_source"), "vector_documents", ["source"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_vector_documents_source"), table_name="vector_documents")
    op.drop_index(op.f("ix_vector_documents_id"), table_name="vector_documents")
    op.drop_table("vector_documents")
    # ### end Alembic commands ###
