scalarData = [
    {
        "deviceCategoryCode": "NAV",
        "locationCode": "CBYDS",
        "hasData": True,
        "possiblePropertyCodes": ["depth", "latitude", "longitude"],
    },
    {
        "deviceCategoryCode": "AISRECEIVER",
        "locationCode": "CBY",
        "hasData": False,
        "possiblePropertyCodes": [],
    },
    {
        "deviceCategoryCode": "ROV_CAMERA",
        "locationCode": "CBYDS",
        "hasData": False,
        "possiblePropertyCodes": [],
    },
    {
        "deviceCategoryCode": "DIVE_COMPUTER",
        "locationCode": "CBYDS",
        "hasData": True,
        "possiblePropertyCodes": ["depth", "seawatertemperature"],
    },
    {
        "deviceCategoryCode": "JB",
        "locationCode": "CBYIJ.J1",
        "hasData": True,
        "possiblePropertyCodes": [
            "amperage",
            "electricalresistance",
            "groundfault",
            "internaltemperature",
            "statuscode",
            "voltage",
        ],
    },
    {
        "deviceCategoryCode": "ICEPROFILER",
        "locationCode": "CBYIP",
        "hasData": True,
        "possiblePropertyCodes": [
            "icedraft",
            "pingtime",
            "seawatertemperature",
            "soundpressurelevel",
            "targetpersistence",
            "tilt",
            "totalpressure",
        ],
    },
    {
        "deviceCategoryCode": "VIDEOCAM",
        "locationCode": "CBYIP",
        "hasData": True,
        "possiblePropertyCodes": [
            "cameralight",
            "camerapan",
            "cameratilt",
            "focus",
            "zoom",
        ],
    },
    {
        "deviceCategoryCode": "RADIOMETER",
        "locationCode": "CBYIP",
        "hasData": True,
        "possiblePropertyCodes": ["parphotonbased"],
    },
    {
        "deviceCategoryCode": "HYDROPHONE",
        "locationCode": "CBYIP",
        "hasData": True,
        "possiblePropertyCodes": [
            "batterycharge",
            "internalhumidity",
            "internaltemperature",
            "statuscode",
        ],
    },
    {
        "deviceCategoryCode": "NITRATESENSOR",
        "locationCode": "CBYIP",
        "hasData": True,
        "possiblePropertyCodes": ["nitrateconcentration"],
    },
    {
        "deviceCategoryCode": "PLANKTONSAMPLER",
        "locationCode": "CBYIP",
        "hasData": False,
        "possiblePropertyCodes": [],
    },
    {
        "deviceCategoryCode": "CAMLIGHTS",
        "locationCode": "CBYIP",
        "hasData": True,
        "possiblePropertyCodes": ["cameralight"],
    },
    {
        "deviceCategoryCode": "PHSENSOR",
        "locationCode": "CBYIP",
        "hasData": True,
        "possiblePropertyCodes": [
            "amperage",
            "gregoriantime",
            "internalhumidity",
            "internalph",
            "ph",
            "seawatertemperature",
            "voltage",
        ],
    },
    {
        "deviceCategoryCode": "ADCP1200KHZ",
        "locationCode": "CBYIP",
        "hasData": True,
        "possiblePropertyCodes": [
            "magneticheading",
            "pitch",
            "roll",
            "seawatertemperature",
            "soundspeed",
        ],
    },
    {
        "deviceCategoryCode": "OXYSENSOR",
        "locationCode": "CBYIP",
        "hasData": True,
        "possiblePropertyCodes": ["oxygen", "seawatertemperature"],
    },
    {
        "deviceCategoryCode": "CTD",
        "locationCode": "CBYIP",
        "hasData": True,
        "possiblePropertyCodes": [
            "conductivity",
            "density",
            "pressure",
            "salinity",
            "seawatertemperature",
            "sigmat",
            "sigmatheta",
            "soundspeed",
        ],
    },
    {
        "deviceCategoryCode": "ACOUSTICRECEIVER",
        "locationCode": "CBYIP",
        "hasData": False,
        "possiblePropertyCodes": [],
    },
    {
        "deviceCategoryCode": "FLUOROMETER",
        "locationCode": "CBYIP",
        "hasData": True,
        "possiblePropertyCodes": ["chlorophyll"],
    },
    {
        "deviceCategoryCode": "FLNTU",
        "locationCode": "CBYIP",
        "hasData": True,
        "possiblePropertyCodes": ["chlorophyll", "turbidityntu"],
    },
    {
        "deviceCategoryCode": "WETLABS_WQM",
        "locationCode": "CBYIP",
        "hasData": True,
        "possiblePropertyCodes": [
            "chlorophyll",
            "conductivity",
            "density",
            "gassaturation",
            "gregoriantime",
            "oxygen",
            "pressure",
            "resevoirvolume",
            "salinity",
            "seawatertemperature",
            "sigmat",
            "sigmatheta",
            "soundspeed",
            "turbidityntu",
        ],
    },
    {
        "deviceCategoryCode": "TURBIDITYMETER",
        "locationCode": "CBYIP",
        "hasData": True,
        "possiblePropertyCodes": ["turbidityntu"],
    },
    {
        "deviceCategoryCode": "CO2SENSOR",
        "locationCode": "CBYIP.D1",
        "hasData": True,
        "possiblePropertyCodes": [
            "co2concentrationlinearized",
            "co2partialpressure",
            "gasstreampressure",
            "internaltemperature",
            "scientificcount",
        ],
    },
    {
        "deviceCategoryCode": "CO2SENSOR",
        "locationCode": "CBYIP.D2",
        "hasData": True,
        "possiblePropertyCodes": [
            "calibratedphaseangle",
            "co2partialpressure",
            "compensatedphaseangle",
            "seawatertemperature",
        ],
    },
    {
        "deviceCategoryCode": "CO2SENSOR",
        "locationCode": "CBYIP.D3",
        "hasData": True,
        "possiblePropertyCodes": [
            "co2concentrationlinearized",
            "co2partialpressure",
            "gasstreampressure",
            "internaltemperature",
            "scientificcount",
        ],
    },
    {
        "deviceCategoryCode": "OXYSENSOR",
        "locationCode": "CBYIP.D4",
        "hasData": True,
        "possiblePropertyCodes": ["oxygen"],
    },
    {
        "deviceCategoryCode": "CTD",
        "locationCode": "CBYIP.D4",
        "hasData": True,
        "possiblePropertyCodes": [
            "biofoulingprevention",
            "conductivity",
            "density",
            "gregoriantime",
            "pressure",
            "salinity",
            "seawatertemperature",
            "soundspeed",
            "turbidityntu",
        ],
    },
    {
        "deviceCategoryCode": "CAMLIGHTS",
        "locationCode": "CBYIP.K1",
        "hasData": True,
        "possiblePropertyCodes": ["cameralight"],
    },
    {
        "deviceCategoryCode": "CAMLIGHTS",
        "locationCode": "CBYIP.K2",
        "hasData": True,
        "possiblePropertyCodes": ["cameralight"],
    },
    {
        "deviceCategoryCode": "CAMLIGHTS",
        "locationCode": "CBYIP.K3",
        "hasData": True,
        "possiblePropertyCodes": ["cameralight"],
    },
    {
        "deviceCategoryCode": "ORIENTATION",
        "locationCode": "CBYIU",
        "hasData": True,
        "possiblePropertyCodes": ["magneticheading", "pitch", "roll"],
    },
    {
        "deviceCategoryCode": "INTERNAL_DEVICE_MONITOR",
        "locationCode": "CBYIU",
        "hasData": True,
        "possiblePropertyCodes": [
            "dewpoint",
            "internalhumidity",
            "internalpressure",
            "internaltemperature",
        ],
    },
    {
        "deviceCategoryCode": "ADAPTER",
        "locationCode": "CBYIU.AC1",
        "hasData": True,
        "possiblePropertyCodes": ["amperage"],
    },
    {
        "deviceCategoryCode": "ADAPTER",
        "locationCode": "CBYIU.AC2",
        "hasData": True,
        "possiblePropertyCodes": ["onoffsensor"],
    },
    {
        "deviceCategoryCode": "ADAPTER",
        "locationCode": "CBYIU.AC3",
        "hasData": True,
        "possiblePropertyCodes": ["onoffsensor"],
    },
    {
        "deviceCategoryCode": "ADAPTER",
        "locationCode": "CBYIU.AC4",
        "hasData": True,
        "possiblePropertyCodes": ["amperage"],
    },
    {
        "deviceCategoryCode": "ADAPTER",
        "locationCode": "CBYIU.AC5",
        "hasData": True,
        "possiblePropertyCodes": ["onoffsensor"],
    },
    {
        "deviceCategoryCode": "ICE_BUOY",
        "locationCode": "CBYSP",
        "hasData": True,
        "possiblePropertyCodes": ["onoffsensor"],
    },
    {
        "deviceCategoryCode": "VIDEOCAM",
        "locationCode": "CBYSS",
        "hasData": False,
        "possiblePropertyCodes": [],
    },
    {
        "deviceCategoryCode": "AISRECEIVER",
        "locationCode": "CBYSS",
        "hasData": False,
        "possiblePropertyCodes": [],
    },
    {
        "deviceCategoryCode": "BARPRESS",
        "locationCode": "CBYSS",
        "hasData": True,
        "possiblePropertyCodes": ["absolutebarometricpressure"],
    },
    {
        "deviceCategoryCode": "METSTN",
        "locationCode": "CBYSS.M1",
        "hasData": True,
        "possiblePropertyCodes": [
            "airtemperature",
            "barometrictrend",
            "internalhumidity",
            "internaltemperature",
            "rainfallrate",
            "relativebarometricpressure",
            "relativehumidity",
            "solarradiation",
            "uvindex",
            "voltage",
        ],
    },
    {
        "deviceCategoryCode": "METSTN",
        "locationCode": "CBYSS.M2",
        "hasData": True,
        "possiblePropertyCodes": [
            "absolutebarometricpressure",
            "absolutehumidity",
            "airdensity",
            "airtemperature",
            "dewpoint",
            "magneticheading",
            "mixingratio",
            "relativebarometricpressure",
            "relativehumidity",
            "solarradiation",
            "specificenthalpy",
            "wetbulbtemperature",
            "windchilltemperature",
            "winddirection",
            "windspeed",
        ],
    },
    {
        "deviceCategoryCode": "INTERNAL_DEVICE_MONITOR",
        "locationCode": "CBYSU",
        "hasData": True,
        "possiblePropertyCodes": [
            "dewpoint",
            "internalhumidity",
            "internalpressure",
            "internaltemperature",
        ],
    },
    {
        "deviceCategoryCode": "POWER_SUPPLY",
        "locationCode": "CBYSU",
        "hasData": True,
        "possiblePropertyCodes": ["amperage", "voltage"],
    },
    {
        "deviceCategoryCode": "ADAPTER",
        "locationCode": "CBYSU.AC1",
        "hasData": True,
        "possiblePropertyCodes": ["onoffsensor"],
    },
    {
        "deviceCategoryCode": "ADAPTER",
        "locationCode": "CBYSU.AC2",
        "hasData": True,
        "possiblePropertyCodes": ["amperage", "benderelectricalresistance", "voltage"],
    },
    {
        "deviceCategoryCode": "OXYSENSOR",
        "locationCode": "CF240",
        "hasData": True,
        "possiblePropertyCodes": ["gassaturation", "oxygen", "seawatertemperature"],
    },
    {
        "deviceCategoryCode": "CTD",
        "locationCode": "CF240",
        "hasData": True,
        "possiblePropertyCodes": [
            "conductivity",
            "density",
            "depth",
            "pressure",
            "salinity",
            "seawatertemperature",
            "soundspeed",
            "turbidityntu",
        ],
    },
    {
        "deviceCategoryCode": "NAV",
        "locationCode": "CF240",
        "hasData": True,
        "possiblePropertyCodes": ["latitude", "longitude"],
    },
    {
        "deviceCategoryCode": "FLUOROMETER",
        "locationCode": "CF240",
        "hasData": True,
        "possiblePropertyCodes": ["chlorophyll"],
    },
    {
        "deviceCategoryCode": "CDOM",
        "locationCode": "CF240",
        "hasData": True,
        "possiblePropertyCodes": ["cdom"],
    },
    {
        "deviceCategoryCode": "TURBIDITYMETER",
        "locationCode": "CF240",
        "hasData": True,
        "possiblePropertyCodes": ["turbidityntu"],
    },
    {
        "deviceCategoryCode": "CDOM",
        "locationCode": "CF240",
        "hasData": True,
        "possiblePropertyCodes": ["cdom"],
    },
]
