from enum import Enum


class StatusCode(Enum):
    REGULAR_MESSAGE = 1
    PROCESSING_DATA_DOWNLOAD = 2
    PARAMS_NEEDED = 3
    ERROR_WITH_DATA_DOWNLOAD = 4
    LLM_ERROR = 5
    DEPLOYMENT_ERROR = 6
    NO_DATA = 7
    SCALAR_REQUEST_ERROR = 8
